### PR TITLE
docs(storage): add documentation for blob and bucket name property

### PR DESCRIPTION
**Pull request by HemangChothani**
Fixes [82]

### CODE REVIEW

**Review by IlyaFaer — APPROVED** [review]
I think, it's okay, but googlers maybe will ask to add this property into `_PropertyMixin` - who knows

**Review by mf2199 — APPROVED** [review]
LGTM

**Comment by HemangChothani** [comment]
@IlyaFaer @mf2199 Added pydoc (property as a doc string)for property documentation and remove the current one as frank commented on public PR.

**Comment by HemangChothani** [comment]
Merged.

**Pull request closed without merging**
